# Generated by Django 4.1.1 on 2023-09-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_recieved',
            field=models.BooleanField(default=True),
        ),
    ]
