# Generated by Django 4.1.1 on 2023-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_groupquiz_rename_is_recieved_message_is_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
