# Generated by Django 4.1.1 on 2023-10-15 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupquiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupquiz',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupquiz',
            name='joined_members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
