# Generated by Django 4.1.1 on 2023-10-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_groupquiz_created_by_groupquiz_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
