# Generated by Django 4.1.1 on 2023-10-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='mode',
            field=models.CharField(default='multiple_choice', max_length=20),
        ),
    ]
