# Generated by Django 4.1.1 on 2023-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_quiz_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='carrier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
